# ============================
# Base Stage: Install dependencies
# ============================
FROM node:22.12.0 AS base
WORKDIR /app
COPY package.json ./
RUN npm install --ignore-scripts


# ============================
# Development Stage
# ============================
# Development stage
FROM base AS development
ENV NODE_ENV=development
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]


# ============================
# Production Stage: Build application
# ============================
FROM base AS production
ENV NODE_ENV=production
COPY . .
RUN npm run build
FROM nginx:1.26.2-alpine
RUN addgroup -g 1001 appgroup && \
    adduser -u 1001 -G appgroup -D evergarden
COPY --from=production /app/dist /usr/share/nginx/html
USER evergarden
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
