# ============================
# Base Stage
# ============================
FROM node:22.12.0-alpine AS base
WORKDIR /app
COPY package.json ./
RUN npm install


# ============================
# Development Stage
# ============================
FROM base AS development
ENV NODE_ENV=development
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]


# ============================
# Build Stage
# ============================
FROM base AS builder
COPY . .
RUN npm run build

# ============================
# Production Stage
# ============================
FROM nginx:1.26.2-alpine AS production
ENV NODE_ENV=production

RUN addgroup -g 1001 appgroup && \
    adduser -u 1001 -G appgroup -D evergarden && \
    mkdir -p /tmp/nginx && \
    chown -R evergarden:appgroup /tmp/nginx && \
    chown -R evergarden:appgroup /var/cache/nginx && \
    chown -R evergarden:appgroup /var/log/nginx && \
    chown -R evergarden:appgroup /etc/nginx/conf.d && \
    chmod -R 755 /var/cache/nginx && \
    chmod -R 755 /var/log/nginx && \
    chmod -R 755 /etc/nginx/conf.d

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

RUN chown -R evergarden:appgroup /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

USER evergarden
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
