import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { Heart, Download } from 'lucide-react';
import { useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { useNavigate, useParams } from 'react-router-dom';

import Image from '@/components/common/Image';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { FocusCards } from '@/components/ui/focusCards';
import { ScrollArea } from '@/components/ui/scroll-area';
import { findAiModel } from '@/constant/AiModels';
import { capitalize } from '@/utils/capitalise';

export default function ImageDetail() {
  const navigate = useNavigate();
  const { imageId, imageCategory } = useParams();
  const { data, isLoading, isError } = useQuery({
    queryKey: ['imageDetail', imageId],
    queryFn: async () => {
      const response = await Promise.all([
        axios
          .get(`/images/get?limit=12&&category=${capitalize(imageCategory!)}`)
          .then((res) => res.data),
        axios.get(`/images/get/${imageId}`).then((res) => res.data),
      ]);

      const similarImages = response[0].images.filter(
        (image: { _id: string }) => image._id !== imageId
      );
      const targetImage = response[1];
      return { targetImage, similarImages };
    },
    staleTime: 0,
    gcTime: 0,
    refetchOnWindowFocus: false,
  });

  useEffect(() => {
    if (isError) {
      navigate('/error');
    }
  });

  if (isLoading) return null;

  return (
    <div className="container mx-auto px-4 py-8 space-y-8">
      <div className="grid md:grid-cols-2 gap-8">
        <div className="relative aspect-[4/3] overflow-hidden rounded-lg">
          <Image
            src={data?.targetImage.url}
            fill
            alt="Image"
            objectFit="cover"
            className="transition-transform duration-300 hover:scale-105"
          />
        </div>
        <div className="space-y-6">
          <h1 className="text-3xl font-bold">{data?.targetImage.title}</h1>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Avatar>
                <AvatarImage
                  src={data?.targetImage.authorId.profileImage || '/default.webp'}
                  alt="user"
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div>
                <h2 className="text-xl font-semibold">{data?.targetImage.authorId.name}</h2>
                <Badge variant="secondary">{data?.targetImage.category}</Badge>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <Button variant="outline" size="icon" disabled>
                <Heart className="h-4 w-4" />
              </Button>
              <span className="text-sm font-medium">{data?.targetImage.likes}</span>
              <Button variant="outline" size="icon" disabled>
                <Download className="h-4 w-4" />
              </Button>
            </div>
          </div>

          <ScrollArea className="h-1/3 w-full rounded-md border p-4 md:h-2/3">
            <div className="pr-4">
              <ReactMarkdown
                className="prose prose-sm max-w-none text-muted-foreground"
                components={{
                  p: ({ children }) => <p className="mb-4 last:mb-0">{children}</p>,
                  h1: ({ children }) => <h1 className="text-xl font-bold mb-4">{children}</h1>,
                  h2: ({ children }) => <h2 className="text-lg font-bold mb-3">{children}</h2>,
                  ul: ({ children }) => <ul className="list-disc pl-4 mb-4">{children}</ul>,
                  ol: ({ children }) => <ol className="list-decimal pl-4 mb-4">{children}</ol>,
                  li: ({ children }) => <li className="mb-1">{children}</li>,
                }}
              >
                {data?.targetImage.description || ''}
              </ReactMarkdown>
            </div>
          </ScrollArea>

          <div className="flex items-center space-x-2 text-sm text-muted-foreground">
            {findAiModel(parseInt(data?.targetImage.aiModel)).image}
            <span>Generated by {findAiModel(parseInt(data?.targetImage.aiModel)).name}</span>
          </div>
        </div>
      </div>
      <div>
        <h3 className="text-2xl font-semibold mb-4">Similar Images</h3>
        <FocusCards cards={data?.similarImages} type="category" />
      </div>
    </div>
  );
}
