# ============================
# Base Stage
# ============================
FROM node:22.12.0 AS base
WORKDIR /app
COPY package.json ./
RUN npm install

# ============================
# Development Stage
# ============================
FROM base AS development
ENV NODE_ENV=development
EXPOSE 3000
CMD ["npm", "run", "dev"]

# ============================
# Build Stage
# ============================
FROM base AS builder
COPY . .
RUN npm run build

# ============================
# Production Stage
# ============================
FROM node:22.12.0-alpine AS production
WORKDIR /app

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    && npm install bcrypt --build-from-source \
    && apk del python3 make g++

RUN addgroup -g 1001 appgroup && \
    adduser -u 1001 -G appgroup -D evergarden

COPY package.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

RUN chown -R evergarden:appgroup /app

USER evergarden

EXPOSE 3000
CMD ["node", "dist/index.js"]