name: "Clean Up Preview Deployments"

env:
  PROJECT_ID: mern-stack-app-447200
  REGION: northamerica-northeast2
  CLIENT_IMAGE: northamerica-northeast2-docker.pkg.dev/mern-stack-app-447200/image-store/client
  SERVER_IMAGE: northamerica-northeast2-docker.pkg.dev/mern-stack-app-447200/image-store/server

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cleanup-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Cleanup PR Resources
        run: |
          echo "Cleaning up resources for PR #${{ github.event.number }}"
          
          echo "Deleting Cloud Run services..."
          gcloud run services delete violet-store-pr-${{ github.event.number }} \
            --region ${{ env.REGION }} --quiet || true
          gcloud run services delete violet-store-server-pr-${{ github.event.number }} \
            --region ${{ env.REGION }} --quiet || true

          echo "Deleting container images..."
          gcloud container images list-tags ${{ env.CLIENT_IMAGE }} \
            --filter="tags=${{ github.sha }}" \
            --format="get(digest)" | \
          while read digest; do
            if [ ! -z "$digest" ]; then
              gcloud container images delete "${{ env.CLIENT_IMAGE }}@$digest" --quiet || true
            fi
          done

          gcloud container images list-tags ${{ env.SERVER_IMAGE }} \
            --filter="tags=${{ github.sha }}" \
            --format="get(digest)" | \
          while read digest; do
            if [ ! -z "$digest" ]; then
              gcloud container images delete "${{ env.SERVER_IMAGE }}@$digest" --quiet || true
            fi
          done

          echo "Cleanup completed"